#!/usr/bin/env bash
set -e

# Check if --verbose or -V was passed
verbose=false
for arg in "$@"; do
    case "$arg" in
        --verbose|-V) verbose=true; break ;;
    esac
done

if $verbose; then
    echo "Running: make fetch-images"
    make fetch-images
else
    make fetch-images > /dev/null 2>&1
fi

if $verbose; then
    echo "Running: ./doc-builder/build_docs $@"
fi
./doc-builder/build_docs "$@"

exit 0
