#!/usr/bin/env python3

"""Main driver wrapper around the doc_builder/build_docs utility.

This tool wraps the build command to build sphinx-based documentation.

This should be run from the directory that contains the Makefile for
building the documentation.
"""

from doc_builder import build_docs  # pylint: disable=import-error

if __name__ == "__main__":
    build_docs.main()
